[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = true # add `--allow-dirty` to `cargo publish`
